### PR TITLE
perf: reduce amt of objects constructed

### PR DESCRIPTION
**Pull request by ThaUnknown**
minor speed increase

### CODE REVIEW

**Review by gfodor — CHANGES_REQUESTED** [review]
Thanks for this! Mind renaming “encode” and “decode” to make it clear what they are doing now that they are in file level scope? Eg “textToBytes”

**Comment by ThaUnknown** [comment]
I was a bit hammered when I made this, sorry for the ugly code lol

**Comment by gfodor** [comment]
LGTM, thanks for the PR!

**Comment by gfodor** [comment]
fyi this code was actually wrong - encode and decode were swapped and both were missing calls to `bind` to ensure they worked

**Comment by ThaUnknown** [comment]
aaaaa, so drunk me was thinking correctly after all, the original used bind

**Pull request merged**
