### PR TITLE
fix: no remove peers

### PR DESCRIPTION
**Pull request by ThaUnknown**
removes peers removal from worker responses as its unreliable

### CODE REVIEW

**Comment by gfodor** [comment]
Can you elaborate on this?

**Comment by gfodor** [comment]
Oh, noticed it's a draft. Nvmd.

**Comment by ThaUnknown** [comment]
#15

**Comment by gfodor** [comment]
Possible to update this to remove peers that aren't connected, instead of all of them? This is there basically to clean those up i/fwhen they timeout from the signalling side.

**Comment by ThaUnknown** [comment]
> Possible to update this to remove peers that aren't connected, instead of all of them? This is there basically to clean those up i/fwhen they timeout from the signalling side.

that will remove peers who take a long time to connect, which I had happen

**Comment by gfodor** [comment]
The server timeout is 2 minutes and the ICE timeout is typically like 30s. If the peers are taking long to connect I’m guessing they never were going to connect, not that they would eventually.

**Comment by gfodor** [comment]
I’m up for revisiting this cleanup in the way you suggest after we merge the version that maintains active connections. I would need to set up a testing environment and so on to do a full test to make sure that doesn’t regress anything - but the simpler change where we don’t disconnect active ones seems obviously safe so let’s land that first.

**Review by davidglezz — APPROVED** [review]

**Pull request closed without merging**
